In [1]:
import numpy as np

In [2]:
#1D array
num=np.array([1,2,3,4,5,6,7,8])
num

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
num[0:5]

array([1, 2, 3, 4, 5])

In [4]:
num[-4:-1]

array([5, 6, 7])

In [7]:
#2D Array
num=np.arange(24).reshape(4,6)
num

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [9]:
num[0,3:]

array([3, 4, 5])

In [11]:
num[0:5:2,1:4:2]

array([[ 1,  3],
       [13, 15]])

In [17]:
#0,5,18,23
num[0:5:3,0:6:5]

array([[ 0,  5],
       [18, 23]])

In [ ]:
#3D Array
a=np.arange(60).reshape(3,4,-1) #also works (3,4,5) 
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [25]:
a[1][2]

array([30, 31, 32, 33, 34])

In [30]:
#21,23,31,33
a[1,0:3:2,1:4:2]

array([[21, 23],
       [31, 33]])

In [38]:
a[[1,2],[3,0],:]

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [ ]:
a.reshape(-1) #reshape helps in flattening

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [42]:
a=np.arange(12).reshape(3,4)
np.mean(a)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
np.mean(a,axis=0) #axis=0 meaning col

array([4., 5., 6., 7.])

In [ ]:
np.mean(a,axis=1) #axis=0 meaning row

array([1.5, 5.5, 9.5])

In [47]:
np.median(a)
np.median(a,axis=0) 

array([4., 5., 6., 7.])

In [48]:
np.median(a)
np.median(a,axis=1) 

array([1.5, 5.5, 9.5])

In [ ]:
np.var(a)

np.float64(11.916666666666666)

In [51]:
np.std(a,axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [ ]:
np.std(a,axis=1)

array([1.11803399, 1.11803399, 1.11803399])