In [1]:
! pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.4 MB 4.7 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.4 MB 5.3 MB/s eta 0:00:02
   ------------- -------------------------- 4.2/12.4 MB 6.0 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.4 MB 6.6 MB/s eta 0:00:01
   --------------------- ------------------ 6.8/12.4 MB 6.4 MB/s eta 0:00:01
   ---------------------- ----------------- 7.1/12.4 MB 5.6 MB/s eta 0:00:01
   --------------------------- ------------ 8.4/12.4 MB 5.5 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.4 MB 5.0 MB/s eta 0:00:01
   ------------------------------ --------- 9.4/12.4 MB 4.7 MB/s eta 0:00:01
   -------------------------------- ------- 10.0/12.4 MB 4.4 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.4 MB 4.2 MB/s eta 0:00:01
   --------

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
type(a)
a

array([1, 2, 3, 4, 5, 6])

In [5]:
from numpy import random
a=np.random.random(10)
a

array([0.81994985, 0.81129935, 0.51765117, 0.3319317 , 0.95013255,
       0.9402621 , 0.33398923, 0.83063945, 0.82430792, 0.8984647 ])

In [6]:
a=np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
#identity
a=np.identity(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
a1=np.arange(12)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
a.ndim
a.shape

(5, 5)

In [17]:
a=np.arange(24).reshape(2,2,3,2)
a

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]]])

In [18]:
a1=np.arange(10)
a1[4]

np.int64(4)

In [20]:
a1=np.arange(10).reshape(2,5)
print(a1)
a1[1][2]
# print(a[1,2])

[[0 1 2 3 4]
 [5 6 7 8 9]]


np.int64(7)

In [21]:
a1=np.arange(12).reshape(2,2,3)
print(a1)
a1.shape
print(a1[0,1,1]) #4

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
4
