In [ ]:
"""
1D Array Slicing
Given the following 1D array:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
1. Extract elements from index 2 to 6 (exclusive of 6).
2. Extract every second element from the entire array.
3. Reverse the entire array using slicing.
4. Extract the last 4 elements.
5. Extract elements from index 1 to 7 with a step of 2.
"""
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print(f"Array: {arr}")

print(f"Elements from index 2 to 6: {arr[2:6]}")
print(f"Second element from entire array: {arr[::2]}")
print(f"Reversed array using slicing: {arr[::-1]}")
print(f"Last 4 elements: {arr[-4:]}")
print(f"Elements from index 1 to 7 with step of 2: {arr[1:7:2]}")

Array: [10 20 30 40 50 60 70 80 90]
Elements from index 2 to 6: [30 40 50 60]
Second element from entire array: [10 30 50 70 90]
Reversed array using slicing: [90 80 70 60 50 40 30 20 10]
Last 4 elements: [60 70 80 90]
Elements from index 1 to 7 with step of 2: [20 40 60]


In [36]:
"""
2D Array Slicing
Given the following 2D array:
arr_2d = np.array([
[1, 2, 3, 4, 5],
[6, 7, 8, 9, 10],
[11, 12, 13, 14, 15],
[16, 17, 18, 19, 20]
])
1. Extract the entire second row.
2. Extract the entire third column.
3. Extract every alternate column from all rows.
4. Extract the bottom-right 2x2 sub-array.
"""
arr_2d = np.array([
[1, 2, 3, 4, 5],
[6, 7, 8, 9, 10],
[11, 12, 13, 14, 15],
[16, 17, 18, 19, 20]
])

print(arr_2d)
print(f"2nd row:\n {arr_2d[1]}")
print(f"3rd column:\n {arr_2d[:,2]}")
print(f"Alternate column from all rows:\n {arr_2d[:,::2]}")
print(f"Bottom right 2x2 sub-array:\n {arr_2d[-2:,-2:]}")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
2nd row:
 [ 6  7  8  9 10]
3rd column:
 [ 3  8 13 18]
Alternate column from all rows:
 [[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]]
Bottom right 2x2 sub-array:
 [[14 15]
 [19 20]]


In [51]:
"""
3D Array Slicing
Given the following 3D array:
arr_3d = np.arange(1, 25).reshape(2, 3, 4)
# Shape: (2, 3, 4)
1. Extract the second row from every 2D slice.
2. Extract the last column from every 2D slice.
3. Extract a sub-array of shape (2, 2, 2) from the top-left corner of each 2D slice.
4. Extract elements of all corners only 0 row and last row
"""
arr_3d = np.arange(1, 25).reshape(2, 3, 4)

print(f"\n3D Array:\n {arr_3d}")
print(f"\n2nd row from every slices:\n {arr_3d[:,1,:]}")
print(f"\nLast column from every 2D slice:\n {arr_3d[:,-1]}")
print(f"\nSub-array of shape (2, 2, 2) from the top-left corner of each 2D slice\n {arr_3d[:,:2,:2]}")


3D Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

2nd row from every slices:
 [[ 5  6  7  8]
 [17 18 19 20]]

Last column from every 2D slice:
 [[ 9 10 11 12]
 [21 22 23 24]]

Sub-array of shape (2, 2, 2) from the top-left corner of each 2D slice
 [[[ 1  2]
  [ 5  6]]

 [[13 14]
  [17 18]]]


In [50]:
print(f"\nCorners of first and last row:\n {arr_3d[:,[0,-1],:][:,:,[0,-1]]}")


Corners of first and last row:
 [[[ 1  4]
  [ 9 12]]

 [[13 16]
  [21 24]]]


In [ ]:
"""
Skewness Calculation of Raw Data
Dataset:
data1 = [12, 15, 14, 10, 18, 20, 22, 25, 13, 17, 19, 21, 16, 14, 23]
data2 =[5, 7, 8, 9, 10, 12, 15, 18, 22, 30, 45, 60]
"""
data1 = [12, 15, 14, 10, 18, 20, 22, 25, 13, 17, 19, 21, 16, 14, 23]

# Step 1: Mean
mean = np.mean(data1)

# Step 2: Standard deviation
std = np.std(data1)

# Step 3: Skewness
skewness = np.mean((data1 - mean) ** 3) / (std ** 3)

print("Mean:", mean)
print("Standard Deviation:", std)
print("Skewness:", skewness)

Mean: 17.266666666666666
Standard Deviation: 4.2184778718817
Skewness: 0.12803035988246825


In [59]:
data2 = np.array([5, 7, 8, 9, 10, 12, 15, 18, 22, 30, 45, 60])

mean = np.mean(data2)
std = np.std(data2)

skewness = np.mean((data2 - mean) ** 3) / (std ** 3)

print("Mean:", mean)
print("Standard Deviation:", std)
print("Skewness:", skewness)

Mean: 20.083333333333332
Standard Deviation: 16.281166693111675
Skewness: 1.3431755308450155
