In [2]:
import numpy as np

In [13]:
"""
Create a 1D NumPy array containing the numbers from 10 to 50 (inclusive) with a step of 5.
● Print the entire array. 
● Access and print the 3rd element. 
● Access and print the last element using negative indexing. 
"""
arr=np.arange(10,55,5)
#Display entire array
print(f"Array: {arr}")

#Display 3rd element
print(f"3rd element is: {arr[2]}")

#Last element
print(f"Last element usig negative indexing: {arr[-1]}")

Array: [10 15 20 25 30 35 40 45 50]
3rd element is: 20
Last element usig negative indexing: 50


In [9]:
"""
Create a 2D NumPy array of shape (3, 4) filled with numbers from 1 to 12 (row-wise). 
● Print the entire array. 
● Access and print the element at row 1, column 2.
"""
arr=np.arange(1,13).reshape(3,4)
#Display array
print("2D Array:")
print(arr)

#Displaying row 1, column 2
print("Element at row 1, column 2:", arr[1][2])

2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element at row 1, column 2: 7


In [15]:
"""
3. Create a 3D NumPy array of shape (2, 3, 4) filled with sequential numbers starting from 
1. 
● Print the entire array. 
● Access and print the element at depth 0, row 1, column 2.
"""
arr=np.arange(1,25).reshape(2,3,4)

#Display array
print("3D Array:")
print(arr)

print("Element at depth 0, row 1, column 2:", arr[0][1][2])

3D Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Element at depth 0, row 1, column 2: 7


In [33]:
"""
4. Calculate mean median Variance, Standard deviation of  
a. 12,32,56,32,87,65,45,32,12,32 
b. 34,56,87,98,12,43,21,45,67,87,22,43
"""
a=[12,32,56,32,87,65,45,32,12,32 ]
b=[34,56,87,98,12,43,21,45,67,87,22,43]

In [ ]:
#Mean
mean_a=np.mean(a)
mean_b=np.mean(b)

print(f"Mean of A is : {mean_a}")
print(f"Mean of B is : {mean_b}")

Mean of A is : 40.5
Mean of A is : 51.25


In [19]:
#Median
median_a=np.median(a)
median_b=np.median(b)

print(f"Median of A is: {median_a}")
print(f"Median of B is: {median_b}")

Median of A is: 32.0
Median of B is: 44.0


In [ ]:
#Variance
variance_a=np.var(a)
variance_b=np.var(b)

print(f"Variance of A is: {variance_a}")
print(f"Variance of B is: {variance_b:.2f}")

Variance of A is: 493.65
Variance of B is: 733.02


In [ ]:
#Standard Deviation
std_dev_a=np.std(a)
std_dev_b=np.std(b)

print(f"Standard Deviation of A:{std_dev_a:.2f}")
print(f"Standard Deviation of B:{std_dev_b:.2f}")

Standard Deviation of A:22.22
Standard Deviation of B:27.07
