In [1]:
import numpy as np

In [2]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
a=np.identity(2)
a

array([[1., 0.],
       [0., 1.]])

In [21]:
a=np.arange(1,10)
print(a)
a[3]

[1 2 3 4 5 6 7 8 9]


np.int64(4)

In [22]:
import numpy as np

arr = np.arange(24).reshape(2, 3, 4)
result = arr[0, 1:, ::2]
print(result.shape)
print(result)

(2, 2)
[[ 4  6]
 [ 8 10]]


In [24]:
import numpy as np
from scipy import stats

data = np.array([10, 20, 30, 40, 50])
z_scores = stats.zscore(data, ddof=1)

In [25]:
import numpy as np

tensor_4d = np.ones((2, 3, 4, 5))
result = tensor_4d.sum(axis=(0, 3))
print(result.shape)

(3, 4)


In [37]:
import numpy as np

a = np.ones((4, 1, 3))
print(a.shape)
b = np.ones((5, 3))
print(b.shape)
c = a + b
print(c.shape)

(4, 1, 3)
(5, 3)
(4, 5, 3)


In [38]:
import numpy as np
arr = np.array([1, 2.5, 3], dtype=np.int32)
print(arr)

[1 2 3]


In [42]:
a = np.arange(120).reshape(2, 3, 4, 5)
b = a[1:2, ..., ::2, 3]
b.shape

(1, 3, 2)

In [43]:
a = np.arange(24).reshape(2, 3, 4)
idx1 = np.array([[0], [1]])
idx2 = np.array([1, 2])
print(a[idx1, idx2].shape)

(2, 2, 4)


In [44]:
a = np.array([[1, 2], [3, 4]])
b = a[a > 1]
b[0] = 99
print(a[0, 1])

2


In [45]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = a[::2, :]
b[0, 0] = 99
print(a[0, 0])

99


In [51]:
a = np.arange(6)
condlist = [a < 2, a > 4]
choicelist = [a * 10, a * 100]
print(np.select(condlist, choicelist, default=-1))

[  0  10  -1  -1  -1 500]


In [48]:
a = np.arange(12).reshape(3, 2, 2)
result = a.sum(axis=2)
result.shape

(3, 2)

In [49]:
a = np.arange(24).reshape(2, 3, 4)
print(a[:, [0, 2], 1:3].shape)

(2, 2, 2)


In [50]:
a = np.array([[1, 2], [3, 4]])
print(np.where(a > 2, a, a * 10))

[[10 20]
 [ 3  4]]


In [52]:
a = np.arange(24).reshape(2, 3, 4)
print(a.transpose(2, 0, 1).shape)

(4, 2, 3)


In [54]:
a = np.ones((2, 3, 4, 5))
b = np.swapaxes(a, 1, 3)
b.shape

(2, 5, 4, 3)

In [55]:
a = np.array([1, 2, 3])      # shape (3,)
b = np.array([[10], [20]])   # shape (2, 1)
print((a + b).shape)

(2, 3)


In [56]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(zscore(a, axis=1).shape)

NameError: name 'zscore' is not defined