In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

In [2]:

data_path = "Advertising.csv"
df = pd.read_csv(data_path,index_col=0)
df.head()

,TV,radio,newspaper,sales
1,230.1,37.8,69.2,22.1
2,44.5,39.3,45.1,10.4
3,17.2,45.9,69.3,9.3
4,151.5,41.3,58.5,18.5
5,180.8,10.8,58.4,12.9


In [3]:
fig = go.Figure()
fig.add_trace(go.Scatter3d(x = df["TV"], y=df["radio"],z=df["sales"]))
fig.show()

In [4]:
df.shape

(200, 4)

In [5]:
df.shape[0]

200

In [6]:
a = np.ones(df.shape[0])
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
x = df[["TV","radio"]].values
X = np.c_[np.ones(df.shape[0]),x]
X

array([[  1. , 230.1,  37.8],
       [  1. ,  44.5,  39.3],
       [  1. ,  17.2,  45.9],
       [  1. , 151.5,  41.3],
       [  1. , 180.8,  10.8],
       [  1. ,   8.7,  48.9],
       [  1. ,  57.5,  32.8],
       [  1. , 120.2,  19.6],
       [  1. ,   8.6,   2.1],
       [  1. , 199.8,   2.6],
       [  1. ,  66.1,   5.8],
       [  1. , 214.7,  24. ],
       [  1. ,  23.8,  35.1],
       [  1. ,  97.5,   7.6],
       [  1. , 204.1,  32.9],
       [  1. , 195.4,  47.7],
       [  1. ,  67.8,  36.6],
       [  1. , 281.4,  39.6],
       [  1. ,  69.2,  20.5],
       [  1. , 147.3,  23.9],
       [  1. , 218.4,  27.7],
       [  1. , 237.4,   5.1],
       [  1. ,  13.2,  15.9],
       [  1. , 228.3,  16.9],
       [  1. ,  62.3,  12.6],
       [  1. , 262.9,   3.5],
       [  1. , 142.9,  29.3],
       [  1. , 240.1,  16.7],
       [  1. , 248.8,  27.1],
       [  1. ,  70.6,  16. ],
       [  1. , 292.9,  28.3],
       [  1. , 112.9,  17.4],
       [  1. ,  97.2,   1.5],
       [  

In [8]:
Y = df[["sales"]].values

In [9]:
def mlr(x,y):
  coff_b =np.linalg.inv(x.T @ x) @ x.T @ y
  return coff_b


In [10]:
b = mlr(X,Y)
b.shape

(3, 1)

In [11]:
y_pred = X @ b
y_pred

array([[20.55546463],
       [12.34536229],
       [12.33701773],
       [17.61711596],
       [13.22390813],
       [12.51208449],
       [11.71821241],
       [12.10551553],
       [ 3.7093792 ],
       [12.55169696],
       [ 7.0358597 ],
       [17.25652015],
       [10.60866187],
       [ 8.81095051],
       [18.44466773],
       [20.82891539],
       [12.90386507],
       [23.24107626],
       [ 9.94121476],
       [14.15384619],
       [18.12139161],
       [14.74206357],
       [ 6.51417168],
       [16.54402663],
       [ 8.14035215],
       [15.6080206 ],
       [14.96769383],
       [17.0463346 ],
       [19.39954145],
       [ 9.15929748],
       [21.64292187],
       [11.35791808],
       [ 7.65045928],
       [18.83346334],
       [ 7.56302763],
       [16.99280099],
       [23.36720719],
       [15.6258994 ],
       [ 9.91257829],
       [20.4405801 ],
       [16.37872122],
       [17.29870935],
       [21.5621537 ],
       [13.96692266],
       [ 8.9009974 ],
       [15