Numpy

In [ ]:
import numpy as np

In [ ]:
# 1D array
a = np.array([1,2,3,4,5,6,7,8])
print(a)

[1 2 3 4 5 6 7 8]


In [ ]:
a[0:5]

array([1, 2, 3, 4, 5])

In [ ]:
a[-4:-1]

array([5, 6, 7])

In [ ]:
#2D array
a = np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
a[0:5:2,1:4:2]

array([[ 1,  3],
       [13, 15]])

In [ ]:
# 3D Array
a =  np.arange(60).reshape(3,4,-1)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [ ]:
a[[0,1],[3,0],:]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.mean(a,axis = 1) # axis  =0 col,1 row

array([1.5, 5.5, 9.5])

In [ ]:
np.median(a,axis=  1)

array([1.5, 5.5, 9.5])

In [ ]:
np.var(a,axis =1)

array([1.25, 1.25, 1.25])

In [ ]:
np.std(a)

np.float64(3.452052529534663)

In [ ]:
pip install spicy

In [ ]:
from spicy import stats
a = np.array([1,2,3,15])
a

array([ 1,  2,  3, 15])

In [ ]:
print(stats.skew(a))

1.1012038049920219
