In [ ]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [19]:
import numpy as np
# creating n-array
a = np.array([1,2,3,4,5,6]) #array
a


array([1, 2, 3, 4, 5, 6])

In [20]:
type(a)

numpy.ndarray

In [21]:
a = np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [22]:
from numpy import random
a = np.random.random(10) # generate 10 random element with in 0 to 1
a

array([0.39213156, 0.72681463, 0.27041097, 0.23825667, 0.24061937,
       0.39986863, 0.6240451 , 0.06506358, 0.9796141 , 0.97540883])

In [23]:
a = np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
a = np.identity(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
a1 = np.arange(12)
a1.ndim

1

In [27]:
a1.shape

(12,)

In [28]:
a1.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
a = np.arange(24).reshape(2,3,2,2)
a

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [33]:
a1 = np.arange(10)
a1[4]

np.int64(4)

In [37]:
a1 = np.arange(10).reshape(2,5)
print(a1)
# a1[1][2]
print(a1[1,2])


[[0 1 2 3 4]
 [5 6 7 8 9]]
7


In [41]:
a1 = np.arange(12).reshape(2,2,3)
print(a1)
print(a1.shape)

print(a1[0,1,1])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
4
